# https://hackernoon.com/the-only-sane-way-to-setup-fastlane-on-a-mac-4a14cb8549c8

on: push

name: App

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  NODE_VERSION: 12.18.0
  EXPO_SDK_VERSION: 40.0.1
  EXPO_CLI_VERSION: 4.1.6
  TURTLE_VERSION: 0.20.4
  SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}

jobs:


#  test-artifact:
#    name: Test Artifact
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Setup Env
#        uses: ./.github/actions/setup
#      - name: Setup Node
#        uses: actions/setup-node@v2.1.2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#
#      - run: brew install secrethub/tools/secrethub-cli
#
#      - run: |
#          echo "AWS_ACCESS_KEY_ID=$(secrethub read denniske/aoe2companion/aws_access_key_id)" >> $GITHUB_ENV
#          echo "AWS_SECRET_ACCESS_KEY=$(secrethub read denniske/aoe2companion/aws_secret_access_key)" >> $GITHUB_ENV
#
#      - run: aws s3 cp s3://build.aoe2companion.com/expo-project-1ae1668b05de8b5acdb95b0645e5f1e342d7d250.aab expo-project-1ae1668b05de8b5acdb95b0645e5f1e342d7d250.aab
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: expo-project-1ae1668b05de8b5acdb95b0645e5f1e342d7d250.aab
#          path: expo-project-1ae1668b05de8b5acdb95b0645e5f1e342d7d250.aab
#
#      - run: ls -al
#
#
#  test-artifact2:
#    name: Test Artifact2
#    runs-on: macos-latest
#    needs: [test-artifact]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Setup Env
#        uses: ./.github/actions/setup
#      - name: Setup Node
#        uses: actions/setup-node@v2.1.2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#
#      - run: brew install secrethub/tools/secrethub-cli
#
#      - run: |
#          echo "AWS_ACCESS_KEY_ID=$(secrethub read denniske/aoe2companion/aws_access_key_id)" >> $GITHUB_ENV
#          echo "AWS_SECRET_ACCESS_KEY=$(secrethub read denniske/aoe2companion/aws_secret_access_key)" >> $GITHUB_ENV
#
#      - name: Download Artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: expo-project-1ae1668b05de8b5acdb95b0645e5f1e342d7d250.aab
#
#      - run: ls -al
#
#      - run: mv expo-project-1ae1668b05de8b5acdb95b0645e5f1e342d7d250.aab app.aab
#
#      - run: ls -al
#
#      - name: Download Artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: expo-project-1ae1668b05de8b5acdb95b0645e5f1e342d7d250.aab
#          path: app2.aab
#
#      - run: ls -al


  publish:
    name: Publish
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Secrets
        uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
          EXPO_USERNAME: secrethub://denniske/aoe2companion/expo_username
          EXPO_PASSWORD: secrethub://denniske/aoe2companion/expo_password
          SENTRY_AUTH_TOKEN: secrethub://denniske/aoe2companion/sentry_auth_token

      - uses: expo/expo-github-action@v5
        with:
          expo-version: ${{ env.EXPO_CLI_VERSION }}
          expo-username: ${{ env.EXPO_USERNAME }}
          expo-password: ${{ env.EXPO_PASSWORD }}
      - run: yarn
      - run: npx expo publish --release-channel $CHANNEL


  build-android:
    name: Build Android
    runs-on: ubuntu-18.04
    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Secrets
        uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
          EXPO_USERNAME: secrethub://denniske/aoe2companion/expo_username
          EXPO_PASSWORD: secrethub://denniske/aoe2companion/expo_password
          EXPO_ANDROID_KEYSTORE_BASE64: secrethub://denniske/aoe2companion/expo_android_keystore_base64
          EXPO_ANDROID_KEYSTORE_ALIAS: secrethub://denniske/aoe2companion/expo_android_keystore_alias
          EXPO_ANDROID_KEYSTORE_PASSWORD: secrethub://denniske/aoe2companion/expo_android_keystore_password
          EXPO_ANDROID_KEY_PASSWORD: secrethub://denniske/aoe2companion/expo_android_key_password

      - run: yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      - run: yarn
      - run: turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null
      - run: echo $EXPO_ANDROID_KEYSTORE_BASE64 | base64 --decode > expo-project.jks
      - run: "
          turtle build:android
            --config app.json
            --release-channel $CHANNEL
            --keystore-path ./expo-project.jks
            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
            --type app-bundle
            -o expo-project-$TRAVIS_COMMIT.aab
        "

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: expo-project-${{ env.TRAVIS_COMMIT }}.aab
          path: expo-project-${{ env.TRAVIS_COMMIT }}.aab


  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: brew install secrethub/tools/secrethub-cli

      - run: |
          echo "EXPO_USERNAME=$(secrethub read denniske/aoe2companion/expo_username)" >> $GITHUB_ENV
          echo "EXPO_PASSWORD=$(secrethub read denniske/aoe2companion/expo_password)" >> $GITHUB_ENV
          echo "EXPO_APPLE_TEAM_ID=$(secrethub read denniske/aoe2companion/expo_apple_team_id)" >> $GITHUB_ENV
          echo "EXPO_IOS_DIST_P12_PASSWORD=$(secrethub read denniske/aoe2companion/expo_ios_dist_p12_password)" >> $GITHUB_ENV
          echo "EXPO_IOS_DIST_P12_BASE64=$(secrethub read denniske/aoe2companion/expo_ios_dist_p12_base64)" >> $GITHUB_ENV
          echo "EXPO_IOS_PROVISIONING_PROFILE_BASE64=$(secrethub read denniske/aoe2companion/expo_ios_prov_profile_base64)" >> $GITHUB_ENV

      - run: yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      - run: yarn
      - run: turtle setup:ios --sdk-version $EXPO_SDK_VERSION > /dev/null
      - run: echo $EXPO_IOS_DIST_P12_BASE64 | base64 --decode > expo-project_dist.p12
      - run: echo $EXPO_IOS_PROVISIONING_PROFILE_BASE64 | base64 --decode > expo-project.mobileprovision
      - run: "
          turtle build:ios
            --config app.json
            --release-channel $CHANNEL
            --team-id \"$EXPO_APPLE_TEAM_ID\"
            --dist-p12-path ./expo-project_dist.p12
            --provisioning-profile-path ./expo-project.mobileprovision
            -o expo-project-$TRAVIS_COMMIT.ipa
        "

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: expo-project-${{ env.TRAVIS_COMMIT }}.ipa
          path: expo-project-${{ env.TRAVIS_COMMIT }}.ipa


  deploy-android:
    name: Deploy Android
    runs-on: macos-latest
    needs: [build-android]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: brew install secrethub/tools/secrethub-cli

      - run: |
          echo "AWS_ACCESS_KEY_ID=$(secrethub read denniske/aoe2companion/aws_access_key_id)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(secrethub read denniske/aoe2companion/aws_secret_access_key)" >> $GITHUB_ENV
          echo "EXPO_USERNAME=$(secrethub read denniske/aoe2companion/expo_username)" >> $GITHUB_ENV
          echo "EXPO_PASSWORD=$(secrethub read denniske/aoe2companion/expo_password)" >> $GITHUB_ENV
          echo "FASTLANE_SERVICE_ACCOUNT_BASE64=$(secrethub read denniske/aoe2companion/fastlane_service_account_base64)" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: expo-project-${{ env.TRAVIS_COMMIT }}.aab

      - run: mv expo-project-${{ env.TRAVIS_COMMIT }}.aab app.aab

      - uses: expo/expo-github-action@v5
        with:
          expo-version: ${{ env.EXPO_CLI_VERSION }}
          expo-username: ${{ env.EXPO_USERNAME }}
          expo-password: ${{ env.EXPO_PASSWORD }}

#      - run: aws s3 cp s3://build.aoe2companion.com/expo-project-1ae1668b05de8b5acdb95b0645e5f1e342d7d250.aab app.aab

      - run: echo $FASTLANE_SERVICE_ACCOUNT_BASE64 | base64 --decode > play-store-service-account.json

      - run: ls -al

      - run: "
          npx expo upload:android
            --verbose
            --type aab
            --path app.aab
            --key play-store-service-account.json
            --track production
            --release-status draft
        "

  deploy-ios:
    name: Deploy iOS
    runs-on: macos-latest
    needs: [build-ios]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: brew install secrethub/tools/secrethub-cli

      - run: |
          echo "AWS_ACCESS_KEY_ID=$(secrethub read denniske/aoe2companion/aws_access_key_id)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(secrethub read denniske/aoe2companion/aws_secret_access_key)" >> $GITHUB_ENV
          echo "EXPO_APPLE_ID=$(secrethub read denniske/aoe2companion/expo_apple_id)" >> $GITHUB_ENV
          echo "EXPO_APPLE_ID_PASSWORD=$(secrethub read denniske/aoe2companion/expo_apple_id_password)" >> $GITHUB_ENV
          echo "EXPO_APPLE_TEAM_ID=$(secrethub read denniske/aoe2companion/expo_apple_team_id)" >> $GITHUB_ENV
          echo "EXPO_APPLE_AUTH_KEY_P8_BASE64=$(secrethub read denniske/aoe2companion/expo_apple_auth_key_p8_base64)" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: expo-project-${{ env.TRAVIS_COMMIT }}.ipa

      - run: mv expo-project-${{ env.TRAVIS_COMMIT }}.ipa app.ipa

      - run: echo $EXPO_APPLE_AUTH_KEY_P8_BASE64 | base64 --decode > auth_key.p8

      - run: yarn global add turtle-cli@$TURTLE_VERSION
      - run: turtle setup:ios --sdk-version $EXPO_SDK_VERSION
      - run: ls -al

      - run: |
          cd app/ios
          fastlane build_and_deploy_testflight
